name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.12']

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      
    - name: Setup virtual environment and install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install -e ".[dev]"
      
    - name: Run tests
      run: |
        source .venv/bin/activate
        uv run -m pytest
      
    - name: Run linting
      run: |
        source .venv/bin/activate
        uv run -m ruff check .
        uv run -m ruff format --check . 